# Generated by Django 4.1.7 on 2023-04-18 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeBe', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('time', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoffeeBe.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoffeeBe.user')),
            ],
        ),
    ]
